import './bootstrap';
import './toggle-menu';
import './scroll';
import './toggle-answer'
import './input';
import './show-modal'
import './post-form';
import './lazy';
import './slider'
import './sidebar'
import './delete'
import './change-img'
import './sending-posts'
import './add-users'
import './user-access'
import './style-input'
